# mongodb.yaml
# Author: Xitai 
# Deploys MongoDB inside Kubernetes as the raw landing zone for the pipeline

apiVersion: v1
kind: PersistentVolumeClaim  # Request storage for MongoDB data
metadata:
  name: mongodb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

# Creates MongoDB application pod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:7.0
          ports:
            - containerPort: 27017  # MongoDB default port
          volumeMounts:
            - name: mongodb-storage
              mountPath: /data/db  # Where MongoDB stores its data inside the container
      volumes:
        - name: mongodb-storage
          persistentVolumeClaim:
            claimName: mongodb-pvc

# Creates Kubernetes service so other pods can reach MongoDB at "mongodb:27017"
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
  type: ClusterIP